### ISSUE TITLE
初始化失败

### ISSUE THREAD

**Issue by xiankq** [cnSchwarzer/electron-spout#2]
大佬您好，发现了您做的electorn版本spout，我感到非常的意外和惊喜。

但是我按照readme打包并在项目中使用了之后，出现了异常

<img width="553" alt="image" src="https://github.com/cnSchwarzer/electron-spout/assets/26294948/22c158f9-2fc4-4020-991a-443e63ad011e">

我不太熟悉node原生库的开发，十分抱歉占用了宝贵的时间，期望你的回复

**Comment by reitowo** [comment]
可能是编译时架构不正确，你可以试试拉一下最新代码并且-A设置下你的32或64位架构，刚才在我25.8.0的工程重新编译试了下是没问题的

另外重新阅读一下 Readme，新增了一些提示看看是否遗漏了

**Comment by xiankq** [comment]
问题得以有效解决，并且在electron demo上成功运行，并且接收端能获取到画面了，感谢大佬😆😆😆😆
